#!/bin/zsh

echo "🧹 Starting Codebase Cleanup"
echo "============================"

# Create a backup directory for files we're removing
mkdir -p .cleanup-backup/$(date +%Y%m%d_%H%M%S)
BACKUP_DIR=".cleanup-backup/$(date +%Y%m%d_%H%M%S)"

echo "📁 Created backup directory: $BACKUP_DIR"

# Function to safely move files to backup
backup_and_remove() {
    local file="$1"
    if [[ -f "$file" ]]; then
        echo "  📦 Backing up: $file"
        cp "$file" "$BACKUP_DIR/"
        git rm "$file" 2>/dev/null || rm "$file"
    fi
}

echo ""
echo "🗑️  Removing temporary fix scripts..."
backup_and_remove "fix-production-admin.php"
backup_and_remove "fix-production-admin-v2.php"
backup_and_remove "fix-production-admin-v3.php"
backup_and_remove "fix-production-storage.php"
backup_and_remove "cleanup-hardcoded-data.php"
backup_and_remove "fix-env.php"
backup_and_remove "create-admin.php"
backup_and_remove "public/create-admin.php"
backup_and_remove "public/fix-admin.php"
backup_and_remove "public/fix-env.php"

echo ""
echo "🚀 Removing deployment scripts..."
backup_and_remove "deploy-admin-fix.sh"
backup_and_remove "deploy-admin-only-system.sh"
backup_and_remove "deploy-cleanup-fixes.sh"
backup_and_remove "deploy-navigation-updates.sh"
backup_and_remove "deploy-staging.sh"
backup_and_remove "deploy-storage-fix.sh"
backup_and_remove "final-blade-fix.sh"
backup_and_remove "fix-all-blade-errors.sh"
backup_and_remove "fix-blade-syntax.sh"
backup_and_remove "fix-production-env.sh"
backup_and_remove "fix-specific-errors.sh"
backup_and_remove "validate-blade-fixes.sh"
backup_and_remove "validate-blade-syntax.sh"
backup_and_remove "copy-css-to-server.sh"

echo ""
echo "🔧 Removing development/testing scripts..."
backup_and_remove "dev-status.sh"
backup_and_remove "test-migration.sh"
backup_and_remove "troubleshoot-local.sh"
backup_and_remove "validate-local.sh"
backup_and_remove "setup-local.sh"
backup_and_remove "switch-to-docker.sh"
backup_and_remove "switch-to-local.sh"

echo ""
echo "🌐 Removing HTML test files..."
backup_and_remove "test-enhanced-search.html"
backup_and_remove "test-events-search.html"
backup_and_remove "test-rate-limiting.html"
backup_and_remove "test-search-functionality-complete.html"
backup_and_remove "test-search-functionality-comprehensive.html"
backup_and_remove "test-search-functionality-final.html"
backup_and_remove "test-search-transitions.html"
backup_and_remove "test-search.html"
backup_and_remove "test-speakers-search.html"

echo ""
echo "📜 Removing JavaScript test files..."
backup_and_remove "test-no-results-functionality.js"
backup_and_remove "test-real-time-search.js"

echo ""
echo "📚 Removing implementation summary documentation..."
backup_and_remove "ADMIN_ROUTES_ADDED.md"
backup_and_remove "BLADE-FIXES-SUMMARY.md"
backup_and_remove "COMPREHENSIVE_PAYMENT_VALIDATION_REPORT.md"
backup_and_remove "FEATURED_EVENTS_IMPLEMENTATION.md"
backup_and_remove "FINAL_IMPLEMENTATION_SUMMARY.md"
backup_and_remove "FINAL_INTEGRATION_STATUS.md"
backup_and_remove "INVOICE_NOT_EXIST_FIX.md"
backup_and_remove "NODEJS_PAYMENT_SETUP.md"
backup_and_remove "PAYMENT_CONTROLLER_FIX.md"
backup_and_remove "PAYMENT_VALIDATION_REPORT.md"
backup_and_remove "PRODUCTION_READY_SUMMARY.md"
backup_and_remove "ROUTE_CONFLICTS_FIXED.md"
backup_and_remove "TASK_14_IMPLEMENTATION_SUMMARY.md"
backup_and_remove "TASK_2_IMPLEMENTATION_SUMMARY.md"
backup_and_remove "TASK_4_IMPLEMENTATION_SUMMARY.md"
backup_and_remove "TESTING_SUITE_SUMMARY.md"
backup_and_remove "TICKET_DROPDOWN_FIXED.md"
backup_and_remove "TICKET_VIEWS_FIXED.md"
backup_and_remove "UNIPAYMENT_INTEGRATION_STATUS.md"
backup_and_remove "UNIPAYMENT_PRODUCTION_ISSUE_SUMMARY.md"
backup_and_remove "UNIPAYMENT_SANDBOX_ISSUE_ANALYSIS.md"
backup_and_remove "UNIPAYMENT_SUCCESS_SUMMARY.md"
backup_and_remove "UNIPAYMENT_TROUBLESHOOTING_GUIDE.md"
backup_and_remove "WEBHOOK_404_TROUBLESHOOTING.md"
backup_and_remove "WEBHOOK_504_ERROR_FIX.md"
backup_and_remove "WEBHOOK_COMPREHENSIVE_TESTING_SUMMARY.md"
backup_and_remove "WEBHOOK_DEPLOYMENT_CHECKLIST.md"
backup_and_remove "WEBHOOK_QUICK_REFERENCE.md"
backup_and_remove "WEBHOOK_SETUP_GUIDE.md"
backup_and_remove "WEBSITE_STRUCTURE_FIXED.md"

echo ""
echo "🗂️  Removing backup files..."
backup_and_remove ".env.backup"
backup_and_remove ".env.backup.20250823_081303"
backup_and_remove "admin@leadershipsummit.com,"

echo ""
echo "🧪 Removing temporary test files..."
backup_and_remove "tests/Feature/AdminSpeakerSelectionJavaScriptTest.php"
backup_and_remove "tests/Feature/EventSpeakersFrontendRefinementTest.php"
backup_and_remove "tests/Feature/EventSpeakersResponsiveTest.php"
backup_and_remove "tests/Feature/EventSpeakerValidationTest.php"

# Remove payment and webhook tests if they're not needed
echo ""
echo "⚠️  Payment and webhook tests found. Remove manually if no longer needed:"
echo "   - tests/Feature/*Payment*.php"
echo "   - tests/Feature/*Webhook*.php"
echo "   - tests/Unit/Services/*Payment*.php"
echo "   - tests/Unit/Services/*Webhook*.php"

echo ""
echo "✅ Cleanup completed!"
echo "📦 Backup created in: $BACKUP_DIR"
echo ""
echo "Next steps:"
echo "1. Review the changes: git status"
echo "2. Commit the cleanup: git add . && git commit -m 'Clean up temporary files and documentation'"
echo "3. Optionally remove backup directory after confirming everything works"